export type Lesson = { num: number; title: string; duration: string };

export type FreeCourse = {
  id: number;
  petType: 'dog' | 'cat' | 'both';
  breed: string;
  title: string;
  category: 'Obedience' | 'Tricks' | 'Hunting' | 'Agility';
  level: 'Easy' | 'Medium' | 'Advanced';
  weeks: number;
  lessonCount: number;
  rating: number;
  reviews: number;
  ageNote: string;
  xpReward: number;
  lessonList: Lesson[];
};

export type PremiumCourse = {
  id: number;
  breed: string;
  title: string;
  business: string;
  category: 'Obedience' | 'Tricks' | 'Hunting' | 'Agility';
  weeks: number;
  lessonCount: number;
  price: string;
  features: string[];
};

export const FREE_COURSES: FreeCourse[] = [
  {
    id: 0,
    petType: 'dog',
    breed: 'Beagle',
    title: 'Puppy Basics',
    category: 'Obedience',
    level: 'Easy',
    weeks: 3,
    lessonCount: 8,
    rating: 4.9,
    reviews: 312,
    ageNote: 'Ages 8 wks+',
    xpReward: 120,
    lessonList: [
      { num: 1, title: 'Welcome & Bonding Time',  duration: '10 min' },
      { num: 2, title: 'Name Recognition',        duration: '15 min' },
      { num: 3, title: 'The Sit Command',         duration: '20 min' },
      { num: 4, title: 'The Down Command',        duration: '20 min' },
      { num: 5, title: 'The Stay Command',        duration: '25 min' },
      { num: 6, title: 'Come When Called',        duration: '20 min' },
      { num: 7, title: 'Leave It & Drop It',      duration: '25 min' },
      { num: 8, title: 'Putting It All Together', duration: '30 min' },
    ],
  },
  {
    id: 1,
    petType: 'dog',
    breed: 'Labrador',
    title: 'Leash Training',
    category: 'Obedience',
    level: 'Medium',
    weeks: 4,
    lessonCount: 10,
    rating: 4.8,
    reviews: 204,
    ageNote: 'Ages 12 wks+',
    xpReward: 150,
    lessonList: [
      { num: 1,  title: 'Intro to the Leash',        duration: '10 min' },
      { num: 2,  title: 'Putting On the Harness',    duration: '10 min' },
      { num: 3,  title: 'Loose Leash Walking',       duration: '20 min' },
      { num: 4,  title: 'Stop & Start',              duration: '20 min' },
      { num: 5,  title: 'Left & Right Turns',        duration: '20 min' },
      { num: 6,  title: 'Avoiding Distractions',     duration: '25 min' },
      { num: 7,  title: 'Walking Beside You',        duration: '25 min' },
      { num: 8,  title: 'Crossing the Street',       duration: '20 min' },
      { num: 9,  title: 'Off-Leash Recall Practice', duration: '30 min' },
      { num: 10, title: 'Final Walk Assessment',     duration: '30 min' },
    ],
  },
  {
    id: 2,
    petType: 'dog',
    breed: 'Golden Retriever',
    title: 'Sit, Stay, Come',
    category: 'Obedience',
    level: 'Easy',
    weeks: 2,
    lessonCount: 6,
    rating: 4.9,
    reviews: 418,
    ageNote: 'Ages 8 wks+',
    xpReward: 90,
    lessonList: [
      { num: 1, title: 'Lure Training Basics',    duration: '10 min' },
      { num: 2, title: 'Teaching Sit',            duration: '15 min' },
      { num: 3, title: 'Teaching Down',           duration: '15 min' },
      { num: 4, title: 'Teaching Stay',           duration: '20 min' },
      { num: 5, title: 'Teaching Come',           duration: '20 min' },
      { num: 6, title: 'Putting It All Together', duration: '25 min' },
    ],
  },
  {
    id: 3,
    petType: 'dog',
    breed: 'Bulldog',
    title: 'House Training 101',
    category: 'Obedience',
    level: 'Easy',
    weeks: 3,
    lessonCount: 7,
    rating: 4.7,
    reviews: 189,
    ageNote: 'Ages 8 wks+',
    xpReward: 105,
    lessonList: [
      { num: 1, title: 'Understanding Your Puppy\'s Schedule', duration: '10 min' },
      { num: 2, title: 'Setting Up a Potty Spot',             duration: '10 min' },
      { num: 3, title: 'Crate Introduction',                  duration: '15 min' },
      { num: 4, title: 'Recognizing "I Need to Go" Signals',  duration: '15 min' },
      { num: 5, title: 'Overnight Success',                   duration: '20 min' },
      { num: 6, title: 'Handling Accidents Calmly',           duration: '15 min' },
      { num: 7, title: 'Maintaining Good Habits',             duration: '20 min' },
    ],
  },
  {
    id: 4,
    petType: 'dog',
    breed: 'Poodle',
    title: 'Basic Tricks Pack',
    category: 'Tricks',
    level: 'Easy',
    weeks: 3,
    lessonCount: 8,
    rating: 4.8,
    reviews: 276,
    ageNote: 'Ages 10 wks+',
    xpReward: 120,
    lessonList: [
      { num: 1, title: 'Shake / High Five',        duration: '15 min' },
      { num: 2, title: 'Spin & Twist',             duration: '15 min' },
      { num: 3, title: 'Roll Over',                duration: '20 min' },
      { num: 4, title: 'Play Dead',                duration: '20 min' },
      { num: 5, title: 'Fetch & Drop It',          duration: '20 min' },
      { num: 6, title: 'Jump Through a Hoop',      duration: '25 min' },
      { num: 7, title: 'Bow',                      duration: '15 min' },
      { num: 8, title: 'Tricks Showcase Review',   duration: '20 min' },
    ],
  },
  {
    id: 5,
    petType: 'dog',
    breed: 'Border Collie',
    title: 'Advanced Tricks',
    category: 'Tricks',
    level: 'Medium',
    weeks: 5,
    lessonCount: 12,
    rating: 4.6,
    reviews: 94,
    ageNote: 'Ages 6 mo+',
    xpReward: 180,
    lessonList: [
      { num: 1,  title: 'Backflip Foundations',    duration: '20 min' },
      { num: 2,  title: 'Weave Through Legs',      duration: '20 min' },
      { num: 3,  title: 'Jump into Arms',          duration: '25 min' },
      { num: 4,  title: 'Retrieve by Name',        duration: '20 min' },
      { num: 5,  title: 'Count & Bark on Cue',     duration: '20 min' },
      { num: 6,  title: 'Tug on Command',          duration: '15 min' },
      { num: 7,  title: 'Balance a Treat on Nose', duration: '20 min' },
      { num: 8,  title: 'Find the Hidden Toy',     duration: '25 min' },
      { num: 9,  title: 'Soccer Dog',              duration: '25 min' },
      { num: 10, title: 'Stack the Cups',          duration: '25 min' },
      { num: 11, title: 'Open & Close Drawer',     duration: '30 min' },
      { num: 12, title: 'Freestyle Showcase',      duration: '30 min' },
    ],
  },
  {
    id: 6,
    petType: 'dog',
    breed: 'Vizsla',
    title: 'Hunting Intro',
    category: 'Hunting',
    level: 'Advanced',
    weeks: 8,
    lessonCount: 15,
    rating: 4.9,
    reviews: 67,
    ageNote: 'Ages 4 mo+',
    xpReward: 225,
    lessonList: [
      { num: 1,  title: 'Field Safety Basics',        duration: '15 min' },
      { num: 2,  title: 'Steady to Wing',             duration: '20 min' },
      { num: 3,  title: 'Introduction to Gunfire',    duration: '20 min' },
      { num: 4,  title: 'Quartering Patterns',        duration: '25 min' },
      { num: 5,  title: 'Scent Tracking',             duration: '30 min' },
      { num: 6,  title: 'Pointing Basics',            duration: '25 min' },
      { num: 7,  title: 'Retrieve to Hand',           duration: '25 min' },
      { num: 8,  title: 'Water Retrieves',            duration: '30 min' },
      { num: 9,  title: 'Working with a Hunting Partner', duration: '25 min' },
      { num: 10, title: 'Reading the Wind',           duration: '25 min' },
      { num: 11, title: 'Blind Retrieves',            duration: '30 min' },
      { num: 12, title: 'Upland Game Scenarios',      duration: '30 min' },
      { num: 13, title: 'Waterfowl Scenarios',        duration: '30 min' },
      { num: 14, title: 'Field Trial Prep',           duration: '30 min' },
      { num: 15, title: 'Season Opener Simulation',   duration: '35 min' },
    ],
  },
  {
    id: 7,
    petType: 'dog',
    breed: 'Weimaraner',
    title: 'Bird Dog Basics',
    category: 'Hunting',
    level: 'Advanced',
    weeks: 6,
    lessonCount: 12,
    rating: 4.8,
    reviews: 52,
    ageNote: 'Ages 4 mo+',
    xpReward: 180,
    lessonList: [
      { num: 1,  title: 'Introduction to Birds',      duration: '20 min' },
      { num: 2,  title: 'Whoa Command',               duration: '20 min' },
      { num: 3,  title: 'Fetch & Deliver',            duration: '25 min' },
      { num: 4,  title: 'Wing Flapping Desensitization', duration: '20 min' },
      { num: 5,  title: 'Steadiness on Point',        duration: '25 min' },
      { num: 6,  title: 'Walking to Flush',           duration: '25 min' },
      { num: 7,  title: 'Backing Another Dog',        duration: '25 min' },
      { num: 8,  title: 'Gun Introduction',           duration: '20 min' },
      { num: 9,  title: 'Real Field Session 1',       duration: '30 min' },
      { num: 10, title: 'Real Field Session 2',       duration: '30 min' },
      { num: 11, title: 'Handling in Heavy Cover',    duration: '30 min' },
      { num: 12, title: 'Season Readiness Test',      duration: '35 min' },
    ],
  },
  {
    id: 8,
    petType: 'dog',
    breed: 'Australian Shepherd',
    title: 'Agility Foundations',
    category: 'Agility',
    level: 'Medium',
    weeks: 6,
    lessonCount: 10,
    rating: 4.7,
    reviews: 131,
    ageNote: 'Ages 6 mo+',
    xpReward: 150,
    lessonList: [
      { num: 1,  title: 'Intro to Agility Equipment', duration: '15 min' },
      { num: 2,  title: 'The Tunnel',                 duration: '20 min' },
      { num: 3,  title: 'The Jump',                   duration: '20 min' },
      { num: 4,  title: 'The A-Frame',                duration: '25 min' },
      { num: 5,  title: 'The Dog Walk',               duration: '25 min' },
      { num: 6,  title: 'Weave Poles',                duration: '30 min' },
      { num: 7,  title: 'The Teeter-Totter',          duration: '25 min' },
      { num: 8,  title: 'Chaining Obstacles',         duration: '30 min' },
      { num: 9,  title: 'Handling Techniques',        duration: '25 min' },
      { num: 10, title: 'First Mini-Course Run',      duration: '30 min' },
    ],
  },
  // Cat courses
  {
    id: 9,
    petType: 'cat',
    breed: 'Tabby',
    title: 'Clicker Training Intro',
    category: 'Tricks',
    level: 'Easy',
    weeks: 2,
    lessonCount: 5,
    rating: 4.9,
    reviews: 203,
    ageNote: 'All ages',
    xpReward: 75,
    lessonList: [
      { num: 1, title: 'What Is a Clicker?',          duration: '5 min'  },
      { num: 2, title: 'Charging the Clicker',        duration: '10 min' },
      { num: 3, title: 'Click = Treat Timing',        duration: '10 min' },
      { num: 4, title: 'First Behavior: Touch',       duration: '15 min' },
      { num: 5, title: 'Chaining Two Behaviors',      duration: '15 min' },
    ],
  },
  {
    id: 10,
    petType: 'cat',
    breed: 'Siamese',
    title: 'Sit & Stay for Cats',
    category: 'Obedience',
    level: 'Easy',
    weeks: 2,
    lessonCount: 6,
    rating: 4.7,
    reviews: 178,
    ageNote: 'All ages',
    xpReward: 90,
    lessonList: [
      { num: 1, title: 'Getting Your Cat\'s Attention', duration: '10 min' },
      { num: 2, title: 'Luring Into a Sit',             duration: '15 min' },
      { num: 3, title: 'Adding the Cue Word',           duration: '10 min' },
      { num: 4, title: 'Teaching Stay',                 duration: '15 min' },
      { num: 5, title: 'Distance & Duration',           duration: '20 min' },
      { num: 6, title: 'Real-World Practice',           duration: '20 min' },
    ],
  },
  {
    id: 11,
    petType: 'cat',
    breed: 'Persian',
    title: 'Paw, High Five & Fist Bump',
    category: 'Tricks',
    level: 'Medium',
    weeks: 3,
    lessonCount: 6,
    rating: 4.8,
    reviews: 134,
    ageNote: 'Ages 3 mo+',
    xpReward: 90,
    lessonList: [
      { num: 1, title: 'Targeting Your Hand',       duration: '10 min' },
      { num: 2, title: 'Paw on Cue',               duration: '15 min' },
      { num: 3, title: 'High Five',                 duration: '15 min' },
      { num: 4, title: 'Fist Bump',                 duration: '15 min' },
      { num: 5, title: 'Wave on Command',           duration: '20 min' },
      { num: 6, title: 'Trick Chain Showcase',      duration: '20 min' },
    ],
  },
  {
    id: 12,
    petType: 'cat',
    breed: 'Maine Coon',
    title: 'Button & Sound Training',
    category: 'Tricks',
    level: 'Advanced',
    weeks: 4,
    lessonCount: 8,
    rating: 4.9,
    reviews: 89,
    ageNote: 'Ages 6 mo+',
    xpReward: 120,
    lessonList: [
      { num: 1, title: 'Intro to Talking Buttons',      duration: '10 min' },
      { num: 2, title: 'First Word: Outside',           duration: '15 min' },
      { num: 3, title: 'First Word: Play',              duration: '15 min' },
      { num: 4, title: 'First Word: Food',              duration: '15 min' },
      { num: 5, title: 'Two-Button Sentences',          duration: '20 min' },
      { num: 6, title: 'Location Words',                duration: '20 min' },
      { num: 7, title: 'Emotional Vocabulary',          duration: '20 min' },
      { num: 8, title: 'Expanding the Board',           duration: '25 min' },
    ],
  },
];

export const PREMIUM_COURSES: PremiumCourse[] = [
  {
    id: 100,
    breed: 'German Shepherd',
    title: 'Advanced Obedience Pro',
    business: 'K9 Academy',
    category: 'Obedience',
    weeks: 6,
    lessonCount: 20,
    price: '$29.99',
    features: ['HD video lessons', 'Weekly instructor check-ins', 'Certificate'],
  },
  {
    id: 101,
    breed: 'Australian Shepherd',
    title: 'Pro Agility Training',
    business: 'AgilityX',
    category: 'Agility',
    weeks: 8,
    lessonCount: 24,
    price: '$39.99',
    features: ['Course layout videos', 'Live Q&A sessions', 'Equipment guide'],
  },
  {
    id: 102,
    breed: 'Golden Retriever',
    title: 'Therapy Dog Certification',
    business: 'PawCare',
    category: 'Obedience',
    weeks: 10,
    lessonCount: 30,
    price: '$49.99',
    features: ['Vet-reviewed curriculum', 'Certification prep', '1-on-1 coaching'],
  },
];
